### ISSUE TITLE
libgit2 1.2.0 support

### ISSUE THREAD

**Issue by alyssais** [libgit2/pygit2#1090]
Hi, I'm a [Nixpkgs](https://github.com/NixOS/nixpkgs) developer, and we'd [like to](https://github.com/NixOS/nixpkgs/pull/136892) update the version of libgit2 that we're providing to 1.2.0, which was recently released.  But doing this would break every package that uses pygit2:

```
#error You need a compatible libgit2 version (1.1.x)
```

Do you have plans for a new release that is compatible with libgit2 1.2.x?  Thanks!

**Comment by Mindavi** [comment]
See #1089 for someone working on it.

**Comment by alerque** [comment]
Same problem here for Arch Linux. Almost everything else using libgit2 is rebuilt, but this is holding up anything from actually going through.

**Comment by herbygillot** [comment]
And now v1.3.0 of `libgit2` has just been released: https://github.com/libgit2/libgit2/releases

**Comment by alerque** [comment]
@herbygillot This was fixed in Git HEAD (see #1089) but they haven't done a release yet.

**To anybody maintaining this:** Tagging a new release is the only way to relieve the pain downstream.

For others still running into this with tagged releases, the guys over at Homebrew [cooked up this pactch](https://github.com/libgit2/pygit2/pull/1089#issuecomment-920808577) that also worked for Arch Linux packaging to get the last tagged pygit2 release to run against current libgit2 builds.

**Comment by carlocab** [comment]
Here's a patch for 1.3.0: https://raw.githubusercontent.com/Homebrew/formula-patches/54d3a0d1f241fdd4e9229312ced0d8da85d964b1/pygit2/libgit2-1.3.0.patch
