### ISSUE TITLE
List all files in a branch

### ISSUE THREAD

**Issue by mqshen** [libgit2/pygit2#244]
How can I list all files in a branch from bare  repository.
thanks!

**Comment by jleclanche** [comment]
It's a bit jarring that you have to diff to an empty tree to get such basic information imo. Would you consider adding a proper api for it, such as Tree.files() or some such?

**Comment by carlosmn** [comment]
You don't need to diff to get this information any more than you need to diff to get the same information from a real file system. Each `Tree` is iterable, which means you can use `list(tree)` in order to get the list of tree entries; libgit2 also has `git_tree_walk()` which is rather similar to python's `os.walk()` (though it doesn't look like it's available in pygit2 atm). If you'd rather not do the iteration yourself, there's also the `Index` datastructure, which you can read a tree into to get a plain list of pathnames.

**Comment by jleclanche** [comment]
git_tree_walk sounds perfect, if it can be made available in pygit2.

**Comment by alexreg** [comment]
Is `git_tree_walk` available yet?
