### ISSUE TITLE
0.23.2 breaks authentication

### ISSUE THREAD

**Issue by terminalmage** [libgit2/pygit2#583]
The ``callbacks`` argument to ``pygit2.Remote.fetch()`` (new in 0.23.2) is required for authentication now. This means that any code which uses authentication immediately breaks when upgrading to 0.23.2:

```
Traceback (most recent call last):
  File "/home/erik/git/salt/issue28911/salt/utils/gitfs.py", line 1702, in fetch_remotes
    if repo.fetch():
  File "/home/erik/git/salt/issue28911/salt/utils/gitfs.py", line 882, in fetch
    fetch_results = origin.fetch()
  File "/home/erik/saltdev/lib/python2.7/site-packages/pygit2/remote.py", line 378, in fetch
    check_error(err)
  File "/home/erik/saltdev/lib/python2.7/site-packages/pygit2/errors.py", line 64, in check_error
    raise GitError(message)
GitError: authentication required but no callback set
```

Is there a reason this was done in a point release, and without a deprecation path?

**Comment by carlosmn** [comment]
In order to have authentication, you must fill in the authentication callback. There is no way this would have ever worked if you didn't provide it. The error is exactly what one would expect: if the server asks for authentication and you have not provided a way to do that, there is no way to move forward.

**Comment by terminalmage** [comment]
Sorry, but you are incorrect when you say that it would never have worked if a callback was not provided. The code which broke was written when 0.20.3 was released. The way authentication was handled was to first get the remotes via the ``pygit2.Repository.remotes()`` function, and then for the desired remote object ``foo``, assign the UserPass or Keypair object to ``foo.credentials`` before running ``foo.fetch()``. This is the functionality that was changed for 0.23.2, as the changelog specifies [here](https://github.com/libgit2/pygit2#0232-2015-10-11).

What I am wondering is A) why this API change did not preserve backwards compatibility, and B) if there was a better way of specifying the credentials in pre-0.23.2 releases, what is this method. If there is a better way of specifying the credentials in earlier versions, then this would be a great opportunity to beef up the documentation.

**Comment by carlosmn** [comment]
>assign the UserPass or Keypair object to foo.credentials before running foo.fetch(). 

What you're doing there is setting the credentials callback. This way of doing it was a left-over from older design decisions which was only ported over to the libgit2 0.23 way of doing things recently, where we no longer keep a copy of the callbacks in the remote object but ask the user pass them in for the operation.

**Comment by terminalmage** [comment]
OK, then your response to my initial post is more confusing, since I mentioned the brand new ``callbacks`` argument, and then you told me that I should have always been doing that.

The error is most certainly *not* what one would expect when upgrading to a point release of pygit2. Changing the API in a non-backwards-compatible way in a point release is indefensible, it breaks applications.

Do you intend to restore backwards compatibility and provide a deprecation path? If not, feel free to close this, but please take more care in future of the impact of changing the API in a point release.

**Comment by jdavid** [comment]
This is absolutely defensible.

We have never kept backwards compatibility in any release, and we have rarely provided deprecation paths. And the reason is very simple: limited resources. This policy is documented, have you read
http://www.pygit2.org/install.html before blaming? Let me copy it here:

    ! Warning

    Backwards compatibility is not guaranteed even between micro releases. Please check the
    release notes for incompatible changes before upgrading to a new release.

This is a volunteer driven project (not paid). I know there are for-profit companies that benefit from pygit2, and don't contribute back. That's fine, it is how FOSS works. For instance, SaltStack (you work there isn't it ?).

I don't even expect people to say thanks. Just to be respectful.

**Comment by terminalmage** [comment]
In the Salt project, we support multiple Python interfaces to git. Thanks for the information, we'll make sure to add information to our documentation to help our users manage expectations. Those that desire a more stable option will have other options in Salt, such as GitPython.

**Comment by pypingou** [comment]
There is something of a chicken and egg problem gaining contributors to a library with an unstable API.
Unstable APIs make it hard for people to use it in their large projects as they are then burdened with the risk of their code breaking at inopportune times.  If they cannot use it then they won't contribute to it either.

The risk factor is magnified for for-profit organizations because they have their livelihoods riding on the software they are writing.  Where I work there are many people who are interested in python/git integration.  Since the organization is large, I'm sure there are people that know enough C and python to be able to contribute back and help but I know I recommend *not* using pygit2 for any of the larger projects that make money for the company because dealing with its continuous API breakage makes it a pain to use in the long term.

This is not to disregard any of your work, I love it and admire it, but I can only use it for my personal projects until something more stable comes along.

I believe this also relates to the issue 230 about finding a source of funding to make work on pygit2 more sustainable.
