### ISSUE TITLE
if commits.message has some unknow code,there happened some error。

### ISSUE THREAD

**Issue by magicgaro** [libgit2/pygit2#615]
![image](https://cloud.githubusercontent.com/assets/16775931/14311279/155c6748-fc19-11e5-868e-6a23c353186a.png)

**Comment by magicgaro** [comment]
how can i solve it？

**Comment by carlosmn** [comment]
It depends on what the problem is. Is the problem that you're using `u"%s"` as your format string when the message isn't in unicode? Then you would have to do whatever python requires to handle arbitrary encodings in these situations.

Is the problem that the committer specified an incorrect encoding for the commit message? In that case you can use [Commit.raw_message](http://www.pygit2.org/objects.html#pygit2.Commit.raw_message) to get the bytes and perform the detection yourself.

**Comment by magicgaro** [comment]
because it has this error, so i used the u"%s  to specify the code.
![image](https://cloud.githubusercontent.com/assets/16775931/14338018/c4ef2786-fca5-11e5-9082-f6e0ad21dc4c.png)

**Comment by jdavid** [comment]
there's `commit.raw_message` that returns bytes
