### ISSUE TITLE
To find diff of two branches

### ISSUE THREAD

**Issue by leongkui** [libgit2/pygit2#648]
Hi, found pygit2 today and learning to use it as tool to build our releases.  One thing I have yet found solution is to generate file(s) changed between two branches.  By using git command, "git diff branch1...branch2 --name-only", I can obtain this list, any way to do this using pygit2?  Thanks in advance for the help.

**Comment by arcsector** [comment]
Alright, man. Idk if you've figured this out yet, since you haven't closed the issue, but I'll lay you some knowledge since the docs are better. It seems like you already know how to discover a commit and access a tree in that commit. In order to loop through all the differences and get the files changed, here's what you can do:

```python
repo = Repository(discover_repository("/path/to/repo"))
commit = repo.revparse_single("HEAD")
diff = commit.tree.diff_to_tree()
fileschanged = []
for patch in diff:
    fileschanged.append(repo[patch.delta.new_file.oid].name)
fileschanged = set(fileschanged)
```

Try this and if there's any bugs let me know.

**Comment by pypingou** [comment]
Small optimization:
````
fileschanged = set()
for patch in diff:
    fileschanged.add(repo[patch.delta.new_file.oid].name)
````

**Comment by acabrol** [comment]
Dear all repo[patch.delta.new_file.oid doesn't exist anymore. Instead i used repo[patch.delta.new_file.id but it return 0000000000000000000000000000000000000000

repo = pygit2.Repository('.')
last = repo[repo.head.target]
filechanged=[]
for commit in repo.walk(last.id, pygit2.GIT_SORT_TIME):
    diff = commit.tree.diff_to_tree()
    fileschanged = []
    for patch in diff:
        print(patch.delta.new_file.id)

Any idea?
