### ISSUE TITLE
How to solve 'LIBSSH2 not found.'?

### ISSUE THREAD

**Issue by pklim101** [libgit2/pygit2#717]
when I execute the command 'cmake .. -DCMAKE_INSTALL_PREFIX=/usr/local/libgit2',
I have the output bellow：

> 

-- Checking for module 'libcurl' 
--   Found libcurl, version 7.15.5  
-- Could NOT find HTTP_Parser (missing: HTTP_PARSER_INCLUDE_DIR HTTP_PARSER_LIBRARY)   
-- http-parser version 2 was not found; using bundled 3rd-party sources.  
-- Checking for module 'libssh2'  
--   No package 'libssh2' found  
-- LIBSSH2 not found. Set CMAKE_PREFIX_PATH if it is installed outside of the default search path.

there are two module not fund, How can I solve it? thanks!

**Comment by mtangoo** [comment]
When I use self-compile version I set up
`export PKG_CONFIG_PATH=/your/path/to/.pc_file`

**Comment by mtangoo** [comment]
>-- Could NOT find HTTP_Parser (missing: HTTP_PARSER_INCLUDE_DIR HTTP_PARSER_LIBRARY)
I believe libgit2 is expecting some sort of native HTTP parser (I gues you disabled curl or was not found) so it falls back to its third-party http library

**Comment by webknjaz** [comment]
@jdavid I think this can be closed since manylinux1 wheels have been implemented and end-users will not have to compile things on their own all the time.
OTOH ones who would want that probably already know what they are doing + can consult with https://github.com/libgit2/pygit2/blob/c43db44/travis/build-manylinux1-wheels.sh.
