### ISSUE TITLE
clone_repository GitError unclear

### ISSUE THREAD

**Issue by arcsector** [libgit2/pygit2#789]
Hello all,

This will be my last and hopefully final issue. I'm attmpting to clone over ssh, which i can do using `git clone` with the ssh url, but my code is throwing `_pygit2.GitError: unsupported URL protocol`. I am attempting to do this on a Github Enterprise server. Is this an error with the server or an error with my code. Code I've tried:
```python
class MyRemoteCallbacks(pygit2.RemoteCallbacks):
        def credentials(self, url, username_from_url, allowed_types):
                if allowed_types & pygit2.credentials.GIT_CREDTYPE_USERNAME:
                        return pg.Username("$user")
                elif allowed_types & pygit2.credentials.GIT_CREDTYPE_SSH_KEY:
                        return pygit2.Keypair("$user", "id_rsa.pub", "id_rsa", "$pass")
                else:
                        return None
print("Cloning pygit2 over ssh with username variable")
pygit2.clone_repository('ssh://github.company.com/$user/$repo', '$repo.git', callbacks=MyRemoteCallbacks())
```
I also tried:
```python
print("Cloning pygit2 over ssh with username in url")
keypair = pygit2.Keypair("$user", "id_rsa.pub", "id_rsa", "$pass")
MyRemoteCallbacks = pygit2.RemoteCallbacks(credentials=keypair)
pygit2.clone_repository('ssh://git@github.company.com:$user/$repo', '$repo.git', callbacks=MyRemoteCallbacks)
```
Both of these throw the same error. Note: my SSH key has a passphrase associated with it.

**Comment by arcsector** [comment]
Also, what is the fourth value in the `Keypair` function for?

**Comment by arcsector** [comment]
Can I get some notes on this or should I just close it?

**Comment by jdavid** [comment]
I have tested the first version of your script with a private repo in github and it worked. Using the ``git`` username, defined for example in the url:

    git@github.company.com/$user/$repo

Note that instead of:

    return pygit2.Keypair("$user", "id_rsa.pub", "id_rsa", "$pass")

It should read:

    return pygit2.Keypair(username_from_url, "id_rsa.pub", "id_rsa", "$pass")

If you don't pass the username in the url it will do a first call to the callback to get the username using ``GIT_CREDTYPE_USERNAME``; and a second call using ``GIT_CREDTYPE_SSH_KEY``

What error do you get?

**Comment by arcsector** [comment]
For me I cannot use the git username or my real username as it is still throwing a `_pygit2.GitError: unsupported URL protocol`.

**Comment by jdavid** [comment]
That error is raised by libgit2, when ``transport_find_fn`` returns ``GIT_ENOTFOUND``, check ``src/transport.c``

It may be libgit2 is not built with ssh support.

**Comment by arcsector** [comment]
Did i build it wrong, then? I followed the instructions to the letter.

**Comment by jdavid** [comment]
You can check whether you have ssh support or not with:

    bool(pygit2.features & pygit2.GIT_FEATURE_SSH)

**Comment by arcsector** [comment]
Returns True:
```python
Python 3.6.3 (default, Oct  3 2017, 21:45:48)
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pygit2 as pg
>>> bool(pg.features and pg.GIT_FEATURE_SSH)
True
```

**Comment by jdavid** [comment]
Then I don't know...

This is the version of the script you posted, that I have tested with and works for me:

```python
import pygit2

KEY_PUB = "/home/jdavid/.ssh/id_rsa.pub"
KEY = "/home/jdavid/.ssh/id_rsa"
SECRET = "XXX"

class MyRemoteCallbacks(pygit2.RemoteCallbacks):

    def credentials(self, url, username_from_url, allowed_types):
        if allowed_types & pygit2.credentials.GIT_CREDTYPE_USERNAME:
            # Ask for the username if not specified in the url
            print('USERNAME')
            return pygit2.Username("git")
        elif allowed_types & pygit2.credentials.GIT_CREDTYPE_SSH_KEY:
            # Ask for the key and secret
            print('KEY', username_from_url)
            return pygit2.Keypair(username_from_url, KEY_PUB, KEY, SECRET)
        else:
            return None

print("Cloning pygit2 over ssh with username variable")
pygit2.clone_repository('ssh://github.com/libgit2/pygit2.git', '/tmp/pygit2.git', callbacks=MyRemoteCallbacks())
```

If it doesn't work you'll have to debug libgit2, there's only one place where that error message is raised.

**Comment by arcsector** [comment]
Any suggestions for debugging libgit2? I've never had to debug a C library before...

**Comment by jdavid** [comment]
Let's forget about pygit2. Try this code:

```c
#include <git2.h>
#include <git2/sys/transport.h>
#include <stdio.h>

void main()
{
  git_transport *transport;

  int err = git_transport_new(&transport, NULL, "ssh://github.com/libgit2/pygit2.git");
  printf("%d\n", err);
}
```

Call it with:

```sh
gcc test_789.c -lgit2 && ./a.out
```

If it worked you should see a **0**, if it does not you will see a **-1**.

Then to debug I would go for a simple process of edit, build, run. Where editing would be very much about inserting ``printf``. Since there's only one place where this error message is raised, it should not take long.

In the branch ``origin/maint/v0.27`` the file ``src/transport.c`` the line 126 is where that error message is raised:

```c
    if ((error = transport_find_fn(&fn, url, &param)) == GIT_ENOTFOUND) {
        giterr_set(GITERR_NET, "unsupported URL protocol");
        return -1;
```

So ``transport_find_fn`` is returning ``GIT_ENOTFOUND``. That function is just above, line 72. Since you're using Linux that function is rather simple, just a couple of calls to ``transport_find_by_url``.

Apparently ``transport_find_by_url`` is returning ``NULL`` for a ``ssh://`` URL. I would start inserting the ``printf`` there. The loop at line 61, for example:

```c
    /* Find a system transport for this URI */
    for (i = 0; i < GIT_TRANSPORT_COUNT; ++i) {
        d = &transports[i];
        printf("%d: %s\n", i, d->prefix); // <== for example
        if (strncasecmp(url, d->prefix, strlen(d->prefix)) == 0) {
            return d;
        }
    }
```

**Comment by cfbarbero** [comment]
In case anybody runs across this.  I had a similar issue, but SSH support was disabled in libgit2.  It was disabled because I compiled libgit2 on a machine that didn't have libssh installed and therefore libgit2 disabled ssh protocol support.

**Comment by meetpradeepp** [comment]
@cfbarbero Thank you

**Comment by stsoor** [comment]
> Returns True:
> 
> ```python
> Python 3.6.3 (default, Oct  3 2017, 21:45:48)
> [GCC 7.2.0] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import pygit2 as pg
> >>> bool(pg.features and pg.GIT_FEATURE_SSH)
> True
> ```

You are using the and operator instead of the bitwise and (&).

**Comment by arcsector** [comment]
@stsoor 
```python
Python 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 19:29:22) [MSC v.1916 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> bool(1 and 1)
True
>>> bool(1 and 0)
False
```

Not really sure why this is at all a comment... @jdavid I'm going to close this because it's stale.

**Comment by stsoor** [comment]
@arcsector 

> Not really sure why this is at all a comment...

Because this thread is misleading while it could be a good reference when the same problem occurs to others. Your problem clearly happened because you did not compile libgit with SSH support. The misleading part is that you checked for a bool value instead of a bitmask while that is not the supported way to do it.
Check the source and you will se that the actual value of GIT_FEATURE_SSH is 4. Then you can check for yourself that:
```
>>> bool(4 and 1)
True
>>> bool(4 & 1)
False
```
This is an important distinction and indicates that the contradictory results of your check were not a fault of the library, one only has to use the bitwise operator which is NOT an alternative to the `and` operator

**Comment by arcsector** [comment]
@stsoor got it; thanks for the clarification. I'll see if i can find my old workbench settings and get this to actually work correctly.
