### ISSUE TITLE
Move CI for Windows to Travis

### ISSUE THREAD

**Issue by jdavid** [libgit2/pygit2#902]
Now that Travis supports Windows, CI would simpler to maintain if we used only Travis:

- [ ] Run the Windows tests in Travis
- [ ] Generate the Windows artefacts in Travis (at this point we can drop AppVeyor)
- [ ] Include libssh2 in the Windows wheels
- [ ] Automatically upload to Pypi

Tests in AppVeyor are broken since commit 492bc5a8, instead of fixing them move to Travis.

Do not use tox in CI, use tox only to run the tests locally for a number of Python versions. Currently local use of tox is broken, since we started using tox in AppVeyor.

**Comment by webknjaz** [comment]
1) Windows in Travis Ci is still in beta so I'd not jump over right away. AppVeyor is better in this matter.
2) Extra jobs will consume Travis CI capacity affecting both repo and org queues. This will result in longer CI waiting times. I usually recommend load-balancing jobs across CIs because of this.
3) I'd say that tox must be used in CI because it creates an opportunity to keep configuration in one place and act as a glue between different envs. But for this to work well `tox.ini` and CI configs should be refactored. The typical practice would be having `tox --notest` invoked in `install` step and `tox` invoked in `script` step along with setting up `TOXENV=py` env var. This allows to cleanly reuse current `python` from CI jobs. Adding extra jobs will be simplified to just adding a job with a modified `TOXENV` each time.

**Comment by jdavid** [comment]
Even if beta it's worth a try, if it doesn't work we stick with AppVeyor. AppVeyor is slow, trying we'll know whether Travis is slower or faster. But more important than machine time is our developer time. 

Personally I'm quite happy how the tests work with Travis right now, which don't involve tox, they're already fast and simple. But I'm open to alternative PRs.

Anyway fixing the Windows tests is the blocker for the next release, one way or another. Though the next release is going to take a while, so not urgent either.

**Comment by webknjaz** [comment]
I maintain a number of projects and have strong opinions about tox's usefulness as a source of truth for all envs :) Having different ways of running tests means that some of them may end up being invoked incorrectly + having to edit the same thing in multiple places usually results into having part of such places forgotten which in turn creates diverse/inconsistent codebase.

P.S. Here's an example of bringing Python 3.7 into Windows jobs: https://github.com/python/core-workflow/pull/311/files?file-filters%5B%5D=.yml#diff-354f30a63fb0907d4ad57269548329e3R107

**Comment by jdavid** [comment]
Travis for Windows does not yet have specific support for Python, and AppVeyor has been working fine since our changes in May 2019. Closing.
